"""
Specialist C: The Auditor
---------------------------

This module defines the Pydantic-AI agent responsible for verifying the relevance
and completeness of the data retrieved from the Graph Database. It acts as a 
Self-RAG (Retrieval-Augmented Generation) evaluator, automatically triggering 
a retry loop if the generated Cypher query fails to answer the user's question.
"""

from pydantic import BaseModel, Field
from pydantic_ai import Agent

# ==========================================
# 1. DEFINE THE STRUCTURED OUTPUT SCHEMA
# ==========================================

class AuditEval(BaseModel):
    """The structured evaluation rubric outputted by The Auditor."""
    score: float = Field(description="Relevance score between 0.0 and 1.0. 1.0 means perfect relevance to the user's audit question.")
    reasoning: str = Field(description="Explanation of why the score was assigned, pointing out missing data if applicable.")
    rewritten_query: str = Field(description="If score < 0.85, a suggested rewritten audit question to yield better Graph connections. Empty if score is high enough.")

# ==========================================
# 2. INITIALIZE THE PYDANTIC-AI AGENT
# ==========================================

# The Auditor acts as the quality assurance layer before results are shown to the user.
auditor_agent = Agent(
    'gemini-3.1-pro-preview',
    output_type=AuditEval,
    system_prompt=(
        "You are Specialist C: The Auditor. "
        "Your role is to act as a rigorous Self-RAG evaluator for an Agentic Graph-RAG system. "
        "You will be given the original audit question, the Cypher query generated, and the results from the Neo4j Graph. "
        "Score the relevance and completeness of the retrieved facts from 0.0 to 1.0. "
        "If the score is < 0.85, you must autonomously rewrite the original question to be more explicit or structured to help The Detective generate a better query next time."
    )
)

# ==========================================
# 3. EVALUATION LOGIC
# ==========================================

def evaluate_results(original_question: str, cypher_query: str, neo4j_results: str) -> AuditEval:
    """
    Public entry point for result evaluation.
    
    This function forces the LLM to grade the output of the database query against the user's original intent.
    
    Args:
        original_question (str): The question the user originally asked.
        cypher_query (str): The exact graph traversal query generated by The Detective.
        neo4j_results (str): The raw stringified JSON results returned by the Neo4j database.
        
    Returns:
        AuditEval: The graded score, reasoning, and potentially a rewritten question for the retry loop.
    """
    prompt = f"""
    Original Audit Question: {original_question}
    Generated Cypher Query: {cypher_query}
    Retrieved Results: {neo4j_results}
    
    Instructions:
    Evaluate if these retrieved results comprehensively answer the audit question.
    Assign a score. Provide reasoning. If the score is low, suggest a rewritten question.
    """
    
    # Run the evaluation synchronously
    result = auditor_agent.run_sync(prompt)
    return result.data
